# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d44a6940fd60baf618dee1e3d3eceec50a4632639509a697294ec4c5fe683cd96f91aa24ffbaa76fc90d07343878229940377e8f41be713ec5cce81011a7c733

test:
  secret_key_base: 1451027b30bc8343cbbe71fadfba73bf5f90ff085315a658d779784245e4fcd1226dbcbf7c52da55ad84251e8ba75351babaa4d59e96c1001454cc78c1fddc38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
